package com.foodapp.orderservice.domain.enums;

public enum OrderStatus {
    CREATED, PAYMENT_PENDING, PAYMENT_FAILED, PAID,
    CONFIRMED_BY_RESTAURANT, REJECTED_BY_RESTAURANT, RESTAURANT_TIMEOUT,
    PREPARING, READY_FOR_PICKUP, ON_THE_WAY, DELIVERED,
    CANCELLED, EXPIRED, REFUND_REQUESTED, REFUNDED
}
